#!/usr/bin/env python3

# Wrapper for invoking the BSM Modbus Tool directly from this repository for
# development.


import os
import sys


# Add this repository to the python search path.
repo = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, repo)

from bauer_bsm.cli import bsmtool


if __name__ == '__main__':
    sys.exit(bsmtool.main())
