#!/usr/bin/env python3
#
# BSM Python library and command line tool
#
# Copyright (C) 2020 chargeIT mobility GmbH
#
# SPDX-License-Identifier: Apache-2.0
#
# Wrapper for invoking the BSM Modbus Tool directly from this repository for
# development.


import os
import sys


# Add this repository to the python search path.
repo = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, repo)

from bauer_bsm.cli import bsmtool


if __name__ == '__main__':
    sys.exit(bsmtool.main())
