#!/bin/sh

#
# Very simple test for the Modbus Tool command line interface.
#
# Please set the environment variables MBTOOL_DEVICE and MBTOOL_UNIT for your
# environment and run this script.
#


MBTOOL=./mbtool


echo "Simple Modbus Tool invocation test."
echo ""
echo "serial device: $MBTOOL_DEVICE"
echo "unit: $MBTOOL_UNIT"
echo ""


# Output Modbus Tool invocations and abort on error.
set -x
set -e


$MBTOOL --help
$MBTOOL list-blocks
$MBTOOL get-block sm
$MBTOOL set --meta-1="Greetings from Simple Modbus Tool test!"
$MBTOOL get --meta-1
$MBTOOL create-snapshot scs
$MBTOOL get-snapshot scs
$MBTOOL verify-snapshot scs
$MBTOOL dump 40177 294
$MBTOOL main
