#!/bin/bash


ROOT_DIR=$(realpath $(dirname $0)/..)
MODELS_DIR=$ROOT_DIR/bauer_bsm/bsm/models
SCHEMA=$ROOT_DIR/bauer_bsm/sunspec/models/smdx/smdx.xsd


function validate {
    # The name attribute is used throughout the SunSpec models but not declared
    # in the schema. Ignore this issue.
    xmllint --noout --schema $SCHEMA $MODELS_DIR/smdx_*.xml 2>&1 | grep -v " validates$" | grep -v "Schemas validity error : Element 'model', attribute 'name': The attribute 'name' is not allowed." | grep -v "\.xml fails to validate$"
}


REMAINING_ISSUES=$(validate | wc -l)

if [ $REMAINING_ISSUES -gt 0 ]
then
    # Re-run validation to output remaining issues.
    validate
    exit 1
fi
