name: Python Check and Package

on:
  push:
    branches:
      - 'master'
      - 'feature/*'
    tags:
      - 'release-*'
  pull_request:
    branches:
      - 'master'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names.
        flake8 ./bauer_bsm --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./bauer_bsm --count --exit-zero --ignore=E121,E125,E126,E127,E128,E241,E301,E302,E303,E501 --max-line-length=127 --statistics
    - name: Check models
      run: |
        ./tools/validate-models
    - name: Build
      run: |
        # Just build the binary distribution package. A source package would be
        # way larger and could be downloaded on demand from the repository.
        python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-packages
        path: dist
